### ISSUE TITLE
Can I only use CPU to debug and understand it? 

### ISSUE THREAD

**Issue by guotong1988** [facebookresearch/clevr-iep#1]
I don't want to train a whole model and predict. I only want to understand it. Is it possible to debug it, only using CPU without GPU?
Thank you!

**Comment by jcjohnson** [comment]
Right now the code will crash if you don't have a GPU, but this is fixed in https://github.com/facebookresearch/clevr-iep/pull/3.

**Comment by rbgirshick** [comment]
#3 is now merged.
