### ISSUE TITLE
where is the code to generate your dataset?

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/clevr-iep#11]
In your paper, you said that you will open source the code for dataset generation. Where can I find the code?
Thank you so much for your amazing code. I learned a lot from your stanford lectures and your open-sourced codes.

**Comment by aecker** [comment]
We were wondering, too, whether you'd be willing to share the code @jcjohnson. Would be terrific!

**Comment by rbgirshick** [comment]
We are working on releasing it soon. Thanks for your interest!

**Comment by rbgirshick** [comment]
FYI, the dataset generation code is now available here: https://github.com/facebookresearch/clevr-dataset-gen. A big thanks to @jcjohnson for the code release!
