### ISSUE TITLE
preprocess_question

### ISSUE THREAD

**Issue by Victoria2333** [facebookresearch/clevr-iep#23]
Traceback (most recent call last):
  File "scripts/preprocess_questions.py", line 193, in <module>
    main(args)
  File "scripts/preprocess_questions.py", line 88, in main
    'answer_token_to_idx': answer_token_to_idx,
UnboundLocalError: local variable 'answer_token_to_idx' referenced before assignment
I just used your code,but it seems alright,i don't know how to fix it....
Thank you~~

**Comment by gabinsane** [comment]
Hi, I just got the same error during the preprocessing of test questions. Did you manage to solve the issue?

**Comment by ChongjianGE** [comment]
@Victoria2333  Hi, I just got the same error during the preprocessing of test questions. Did you manage to solve the issue?
