### ISSUE TITLE
CLEVR_v1.0 dataset downloaded from this link:https://s3-us-west-1.amazonaws.com/clevr/CLEVR_v1.0.zip, have missed about 85 images in test set

### ISSUE THREAD

**Issue by happylicio** [facebookresearch/clevr-iep#30]
![image](https://user-images.githubusercontent.com/18717873/34426014-224e70ae-ec6d-11e7-8871-960e77c8b711.png)

As shown above, my downloaded test sets don't have 15000 images. Has anybody been facing the same problem?

**Comment by rbgirshick** [comment]
![image](https://user-images.githubusercontent.com/1190634/34427895-f8576542-ebfb-11e7-8ee9-50af58b20878.png)

I've verified that the zip file contains the expected number of images, as shown above. It seems that file you downloaded is corrupted. I suggest to try downloading it again and check that the md5sum is `b11922020e72d0cd9154779b2d3d07d2`.
