### ISSUE TITLE
a possible typo!

### ISSUE THREAD

**Issue by shanenian** [facebookresearch/clevr-iep#34]
Hello,
I am wondering if there is a typo in the command listed in section https://github.com/facebookresearch/clevr-iep/blob/master/TRAINING.md#step-2-train-the-execution-engine, 

python scripts/train_model.py \
  --model_type EE \
  --program_generator_start_from data/program_generator.py \
  --num_iterations 100000 \
  --checkpoint_path data/execution_engine.pt

should "--program_generator_start_from data/program_generator.py \" be "--program_generator_start_from data/program_generator.pt \"?

Please check and confirm it, thanks!

**Comment by mileyan** [comment]
Agree with it.
Before I modify it, the accuracy is only 51%.

**Comment by shanenian** [comment]
what's the accuracy after you modify it? Mine is still around 50%. @mileyan

**Comment by mileyan** [comment]
I find when they train execution_engine.pt, they do not load the program_generator model. So even though there is a typo, it will not have effect on the result. I do not find the bug right now.

**Comment by shanenian** [comment]
yes, I realize that as well after examine the source code. But it seems this code can not reproduce the result in the paper, have you made any progress yet? @mileyan

**Comment by mileyan** [comment]
![download](https://user-images.githubusercontent.com/3722398/35420601-7006fb72-020c-11e8-9d22-9e5aaac1886d.png)
This is the loss curve when I train the execution model. Can you compare with your training log?

**Comment by shanenian** [comment]
yes, your loss plot is similar to mine which stays around at 1. The accuracy of my trained execute engine is around 50% and jointly trained entire model only gets 25% accuracy which is far below the result in the paper. How is your model's accuracy? Have you got better result? @mileyan

**Comment by mileyan** [comment]
No. same as you. You can try lr=1e-4.

**Comment by shanenian** [comment]
by setting lr=1e-4, the execute engine's accuracy is increased to > 90%, thanks! @mileyan

**Comment by ankursikarwar** [comment]
> by setting lr=1e-4, the execute engine's accuracy is increased to > 90%, thanks! @mileyan

Were you getting >90% accuracy by directly training the execution engine (using step 2 in the README)??
