### ISSUE TITLE
torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by monajalal** [facebookresearch/clevr-iep#38]
[jalal@goku clevr-iep]$ pip install -r requirements.txt 
torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
[jalal@goku clevr-iep]$ uname -a
Linux goku.bu.edu 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by monajalal** [comment]
my bad I missed the fact it is for Python 3.5, basically create a conda env for python 3.5 and then run the above command.

**Comment by ysl208** [comment]
I get the same error. I tried setting up a conda environment but it still doesn't work. Does it also work for python 3.7?
