### ISSUE TITLE
Unable to download CLEVR dataset

### ISSUE THREAD

**Issue by vardaan123** [facebookresearch/clevr-iep#45]
The link for downloading CLEVR dataset seems to be down. I get the error 
for https://s3-us-west-1.amazonaws.com/clevr/CLEVR_v1.0.zip
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
```

**Comment by rbgirshick** [comment]
Please see the URL migration implemented in: https://github.com/facebookresearch/clevr-iep/commit/9945fdd6d9f6da8e3d22d2269d96fdd3fdc7d7d9.

**Comment by rbgirshick** [comment]
Btw, @vardaan123 where did you find the old URL? Perhaps we missed changing it in somewhere.

**Comment by vardaan123** [comment]
thanks. I found it on the webpage for CLEVR dataset
https://cs.stanford.edu/people/jcjohns/clevr/

**Comment by rbgirshick** [comment]
@jcjohnson -- flagging that the CLEVR download URL on your website needs an update.

Replace: `s3-us-west-1.amazonaws` with `dl.fbaipublicfiles` as in https://github.com/facebookresearch/clevr-iep/commit/9945fdd6d9f6da8e3d22d2269d96fdd3fdc7d7d9.

**Comment by jcjohnson** [comment]
Done - thanks for the reminder!
