### ISSUE TITLE
Question: A list of program modules

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/clevr-iep#49]
Hey,

In the paper , in section 3.1 , it is mentioned that the syntax is set by pre-speciying a list of functions - F. I assume this is a fixed set of functions or say a vocabulary.

Where is this vocabulary defined in the code? And It is not clear to me how you arrive at this list of functions for the given problem of QA on CLEVER.

Can any of the authors please answer my question. Please excuse if my question is ambiguous

--
thanks

**Comment by jcjohnson** [comment]
The CLEVR dataset provides a program representation for each question. The preprocessing script ingests the raw CLEVR dataset and converts it to the training format expected here; in particular the programs from the CLEVR JSON files are converted into sequences of functions here:

https://github.com/facebookresearch/clevr-iep/blob/master/scripts/preprocess_questions.py#L134
