### ISSUE TITLE
pytorch installation issue!

### ISSUE THREAD

**Issue by loveJasmine** [facebookresearch/clevr-iep#7]
$pip3 list --user
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
h5py (2.7.0)
olefile (0.44)
Pillow (4.1.1)
PyYAML (3.12)
torch (0.1.12.post2)
torchvision (0.1.8)
virtualenv (15.1.0)

however:
$python3 scripts/run_model.py   --program_generator models/CLEVR/program_generator_18k.pt   --execution_engine models/CLEVR/execution_engine_18k.pt   --image img/CLEVR_val_000013.png   --question "Does the small sphere have the same color as the cube left of the gray cube?"
Traceback (most recent call last):
  File "scripts/run_model.py", line 14, in <module>
    import torch
  File "/home/yike.yk/.local/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by jcjohnson** [comment]
This is a PyTorch problem and not specific to this project.

Try the PyTorch forums (https://discuss.pytorch.org/) or GitHub repo (https://github.com/pytorch/pytorch/issues).
