### ISSUE TITLE
Test answers of CLEVR dataset

### ISSUE THREAD

**Issue by joeyhng** [facebookresearch/clevr-iep#9]
Where can I find the test set answers of the CLEVR dataset? Thanks.

**Comment by rbgirshick** [comment]
We are keeping them private for now to prevent overfitting. We may set up an evaluation server (with rate quotas) in the future. For now, if you want to get test set results for a paper please send them to @jcjohnson.

**Comment by Victoria2333** [comment]
@rbgirshick ,I created a json file with question_id and predicted answer,so i just send the file to jcjohnson's email???

**Comment by Victoria2333** [comment]
@joeyhng@rbgirshick 
Usually how long will it take for him to reply???
Looking forward to your reply~~~

**Comment by MikyasDesta** [comment]
@Victoria2333 Did you get a response from @jcjohnson ? It's been more than a month since I sent an email.

**Comment by jcjohnson** [comment]
@MikyasDesta I somehow missed your email, I'm so sorry about that. Just replied.
